Replace deprecated multipart argument memfile_limit with spool_limit
zopefoundation/zope.publisher pull request #79
Opened 2024-10-02 12:17 UTC by stollero

Hello everyone,

`memfile_limit` has been replaced by `spool_limit`, see https://github.com/defnull/multipart/blob/master/multipart.py#L576.

Unfortunately they use `self.spool_limit = memfile_limit or spool_limit`, so if `memfile_limit = 0` it will always be the default `spool_limit` instead.

2024-10-23 09:06 UTC, mgedmin reviewed
Looks good if we make sure setup.py requires multipart >= the version that added the `spool_limit` argument.  What version was it, by the way?

2024-10-23 09:08 UTC, mgedmin commented
(You'll want to rebase on git master to fix the CI failure.)

2024-10-23 09:09 UTC, mgedmin commented
I found a button on GitHub that allowed me to rebase your branch.  Hope I didn't step on any toes while doing it!

2024-10-28 08:16 UTC, stollero commented
Thanks for the review. I will update the setup.py 👍 

> Looks good if we make sure setup.py requires multipart >= the version that added the `spool_limit` argument. What version was it, by the way?

The bump to [multipart v1.0.0](https://github.com/defnull/multipart/releases/tag/v1.0.0)

2024-10-29 07:54 UTC, icemac commented
Thank you for your contribution.

According to the contributing policies of the zopefoundation organization you need to sign a contributor agreement before any non-trivial change can be merged. For details please consult the [Contributing guidelines for zopefoundation projects](https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md).

2024-10-29 07:55 UTC, icemac requested changes
I like the changes, additionally I'd like to request an entry in the change log.

2024-10-29 12:41 UTC, stollero commented
@icemac Updated changelog and signed agreement 👍

2024-11-04 08:11 UTC, icemac approved these changes

2024-11-04 08:12 UTC, merged

2024-11-04 08:12 UTC, icemac commented
Thank you for this PR. 😃 And welcome onboard!